name: Synchronize Wiki

on:
  push:
    paths:
      - StepLang.Wiki/**
      - .github/workflows/wiki.yml
    branches:
      - main

env:
  USER_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  USER_NAME: ${{ github.actor }}
  USER_EMAIL: "${{ github.actor }}@users.noreply.github.com"
  OWNER: ${{ github.event.repository.owner.name }}
  REPOSITORY_NAME: ${{ github.event.repository.name }}
  COMMIT_MSG: "${{ github.event.head_commit.message }} (${{ github.sha }})"

jobs:
  sync:
    name: Synchronize Wiki
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Pull GitHub Wiki
        run: git clone https://github.com/$GITHUB_REPOSITORY.wiki.git _wiki
      - name: Update Wiki files
        run: rsync -av --delete StepLang.Wiki/ _wiki/ --exclude .git --exclude StepLang.Wiki.csproj
      - name: Push Docs to GitHub Wiki
        run: pushd _wiki && ./sync.sh && popd
